# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: ctrlx-ignition-edge
version: "8.1.45+dev"
base: core22
summary: Ignition Edge Gateway designed for ctrlX OS
icon: snap/gui/logo.png
description: |
    Ignition Edge® makes edge computing easier and more affordable with far-reaching features for your field devices and OEM equipment. 
    Extend your system with data syncing and system management. Use unlimited tag and device connections to expand data collection, then see it with versatile visualization tools. 
    Run scripts or interface with applications out at the edge, too. Its all possible with Ignition Edge. 
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [arm64]
  - build-on: [amd64]
    build-for: [amd64]

parts:
    ignitionedge:
        plugin: dump
        source: 
            - on amd64 to arm64: ./bin/Ignition-Edge-linux-aarch-64-8.1.45.zip
            - on amd64 to amd64: ./bin/Ignition-Edge-linux-x86-64-8.1.45.zip
        source-type: zip
        override-pull: |
            craftctl default  
            rm lib/core/launch/*.exe
            rm lib/core/launch/*.dmg
            rm lib/core/launch/*.gz
            rm data/ignition.conf
            rmdir temp
            chmod a+x *.sh
            chmod a+x ignition-gateway
            case $SNAPCRAFT_TARGET_ARCH in
            amd64)
                tar -xzf lib/runtime/jre-nix.tar.gz
                mv jre-nix lib/runtime/jre-nix
                ;;
            arm64)
                tar -xzf lib/runtime/jre-aarch64.tar.gz
                mv jre-aarch64 lib/runtime/jre-aarch64
                rm lib/runtime/*.gz
                ;;
            esac       
        organize:
            data: data_tmp/
            logs: logs_tmp/
            user-lib: user-lib_tmp

    snapconfigs: 
        after: 
            - ignitionedge
        plugin: dump
        source:
            - on amd64 to amd64: ./include/amd64
            - on amd64 to arm64: ./include/arm64        
        organize: 
            "ignition.conf": "data_tmp/ignition.conf"
 
    configs:
        source: ./configs
        plugin: dump
        organize:
            'package-assets/*': package-assets/${CRAFT_PROJECT_NAME}/

layout:
    $SNAP/webserver/metro-keystore:
        symlink: $SNAP_DATA/data/local/metro-keystore
    $SNAP/webserver/csr.pfx:
        symlink: $SNAP_DATA/data/local/csr.pfx
    $SNAP/webserver/ssl.pfx:
        symlink: $SNAP_DATA/data/local/ssl.pfx
    $SNAP/lib/install-info.txt:
        bind-file: $SNAP_DATA/lib/install-info.txt
    $SNAP/data:
        symlink: $SNAP_DATA/data
    $SNAP/temp:
        symlink: $SNAP_DATA/temp
    $SNAP/logs:
        symlink: $SNAP_DATA/logs
    $SNAP/user-lib:
        symlink: $SNAP_DATA/user-lib        

apps: 
    ignitionedge:
        command: ./ignition.sh
        plugs:
            - network
            - network-bind
            - network-status
            - removable-media
        daemon: simple
        restart-condition: always
        passthrough:
            restart-delay: 30s    
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib

slots:
    package-assets:
        interface: content
        content: package-assets
        source:
            read:
                - $SNAP/package-assets/${CRAFT_PROJECT_NAME}

