#!/bin/sh -e

# Create the files in SNAP_DATA area
if [ ! -d $SNAP_DATA/logs ]; then
    cp -r $SNAP/logs_tmp $SNAP_DATA/logs
fi
#if [ ! -d $SNAP_DATA/data ]; then
#    cp -r $SNAP/data $SNAP_DATA/data
#    cp $SNAP_DATA/data/gateway.xml_clean $SNAP_DATA/data/gateway.xml
#    mkdir $SNAP_DATA/data/local
#fi
if [ ! -d $SNAP_DATA/lib ]; then
    mkdir $SNAP_DATA/lib
    cp $SNAP/lib/install-info.txt $SNAP_DATA/lib/install-info.txt
fi
if [ ! -d $SNAP_DATA/temp ]; then
    mkdir $SNAP_DATA/temp
fi
if [ ! -d $SNAP_DATA/user-lib ]; then
    cp -r $SNAP/user-lib_tmp $SNAP_DATA/user-lib
fi

#mkdir $SNAP_DATA/logs
mkdir $SNAP_DATA/jre-tmp

#preload data directory
cp -r $SNAP/data_tmp/. $SNAP_DATA/data
cp $SNAP/data_tmp/gateway.xml_clean $SNAP_DATA/data/gateway.xml
mkdir $SNAP_DATA/data/local
